import type { SaboreData } from "./types";

const now = "2026-05-03T11:30:00-03:00";

export const demoData: SaboreData = {
  organization: {
    id: "org-sabore",
    name: "Sabore Operacao",
    planPrice: 69.9,
  },
  unit: {
    id: "unit-ponta-verde",
    organizationId: "org-sabore",
    name: "Sabore Ponta Verde",
    city: "Maceio",
    neighborhood: "Ponta Verde",
    fiscalEnabled: true,
  },
  users: [
    {
      id: "usr-bruno",
      unitId: "unit-ponta-verde",
      name: "Bruno",
      role: "owner",
    },
    {
      id: "usr-caixa",
      unitId: "unit-ponta-verde",
      name: "Ana Caixa",
      role: "cashier",
    },
    {
      id: "usr-cozinha",
      unitId: "unit-ponta-verde",
      name: "Rafa Cozinha",
      role: "kitchen",
    },
  ],
  tables: [
    { id: "table-1", unitId: "unit-ponta-verde", label: "Mesa 1", seats: 2, status: "open" },
    { id: "table-2", unitId: "unit-ponta-verde", label: "Mesa 2", seats: 4, status: "free" },
    { id: "table-3", unitId: "unit-ponta-verde", label: "Mesa 3", seats: 6, status: "free" },
    { id: "table-4", unitId: "unit-ponta-verde", label: "Mesa 4", seats: 4, status: "closing" },
  ],
  customers: [
    {
      id: "cust-maria",
      unitId: "unit-ponta-verde",
      name: "Maria Eduarda",
      phone: "+5582999991111",
      neighborhood: "Jatiuca",
    },
    {
      id: "cust-victor",
      unitId: "unit-ponta-verde",
      name: "Victor Lima",
      phone: "+5582999992222",
      neighborhood: "Ponta Verde",
    },
  ],
  ingredients: [
    {
      id: "ing-arroz",
      unitId: "unit-ponta-verde",
      name: "Arroz cateto",
      measure: "kg",
      averageCost: 7.8,
      minimumStock: 8,
    },
    {
      id: "ing-salmao",
      unitId: "unit-ponta-verde",
      name: "Salmao fresco",
      measure: "kg",
      averageCost: 72,
      minimumStock: 5,
    },
    {
      id: "ing-camarao",
      unitId: "unit-ponta-verde",
      name: "Camarao limpo",
      measure: "kg",
      averageCost: 58,
      minimumStock: 4,
    },
    {
      id: "ing-tomate",
      unitId: "unit-ponta-verde",
      name: "Tomate italiano",
      measure: "kg",
      averageCost: 9.5,
      minimumStock: 6,
    },
    {
      id: "ing-queijo",
      unitId: "unit-ponta-verde",
      name: "Queijo coalho",
      measure: "kg",
      averageCost: 38,
      minimumStock: 3,
    },
    {
      id: "ing-acai",
      unitId: "unit-ponta-verde",
      name: "Acai polpa",
      measure: "kg",
      averageCost: 18,
      minimumStock: 8,
    },
  ],
  lots: [
    {
      id: "lot-arroz-1",
      ingredientId: "ing-arroz",
      supplier: "Atacadao AL",
      batchCode: "ARZ-0426",
      quantity: 21,
      expiresAt: "2026-08-20",
      receivedAt: "2026-04-25",
    },
    {
      id: "lot-salmao-1",
      ingredientId: "ing-salmao",
      supplier: "Mar Azul",
      batchCode: "SLM-0501",
      quantity: 6.2,
      expiresAt: "2026-05-05",
      receivedAt: "2026-05-01",
    },
    {
      id: "lot-camarao-1",
      ingredientId: "ing-camarao",
      supplier: "Costa Sul",
      batchCode: "CAM-0429",
      quantity: 3.1,
      expiresAt: "2026-05-04",
      receivedAt: "2026-04-29",
    },
    {
      id: "lot-tomate-1",
      ingredientId: "ing-tomate",
      supplier: "Ceasa",
      batchCode: "TOM-0502",
      quantity: 7.8,
      expiresAt: "2026-05-08",
      receivedAt: "2026-05-02",
    },
    {
      id: "lot-queijo-1",
      ingredientId: "ing-queijo",
      supplier: "Laticinio Sertao",
      batchCode: "QJ-0418",
      quantity: 4.4,
      expiresAt: "2026-05-11",
      receivedAt: "2026-04-28",
    },
    {
      id: "lot-acai-1",
      ingredientId: "ing-acai",
      supplier: "Norte Puro",
      batchCode: "ACA-0411",
      quantity: 15,
      expiresAt: "2026-07-02",
      receivedAt: "2026-04-20",
    },
  ],
  products: [
    {
      id: "prd-poke",
      unitId: "unit-ponta-verde",
      name: "Poke salmao da casa",
      category: "Pratos",
      price: 42,
      active: true,
      preparationArea: "kitchen",
    },
    {
      id: "prd-risoto",
      unitId: "unit-ponta-verde",
      name: "Risoto de camarao",
      category: "Pratos",
      price: 56,
      active: true,
      preparationArea: "kitchen",
    },
    {
      id: "prd-tapioca",
      unitId: "unit-ponta-verde",
      name: "Tapioca de queijo coalho",
      category: "Entradas",
      price: 24,
      active: true,
      preparationArea: "kitchen",
    },
    {
      id: "prd-acai",
      unitId: "unit-ponta-verde",
      name: "Acai 500 ml",
      category: "Sobremesas",
      price: 28,
      active: true,
      preparationArea: "bar",
    },
  ],
  recipe: [
    { id: "rec-poke-arroz", productId: "prd-poke", ingredientId: "ing-arroz", quantity: 0.18 },
    { id: "rec-poke-salmao", productId: "prd-poke", ingredientId: "ing-salmao", quantity: 0.16 },
    { id: "rec-poke-tomate", productId: "prd-poke", ingredientId: "ing-tomate", quantity: 0.08 },
    { id: "rec-risoto-arroz", productId: "prd-risoto", ingredientId: "ing-arroz", quantity: 0.14 },
    { id: "rec-risoto-camarao", productId: "prd-risoto", ingredientId: "ing-camarao", quantity: 0.2 },
    { id: "rec-tapioca-queijo", productId: "prd-tapioca", ingredientId: "ing-queijo", quantity: 0.12 },
    { id: "rec-acai-acai", productId: "prd-acai", ingredientId: "ing-acai", quantity: 0.42 },
  ],
  orders: [
    {
      id: "ord-101",
      unitId: "unit-ponta-verde",
      code: "101",
      channel: "table",
      status: "preparing",
      openedAt: "2026-05-03T11:04:00-03:00",
      tableId: "table-1",
      items: [
        { id: "item-101-1", productId: "prd-poke", quantity: 2 },
        { id: "item-101-2", productId: "prd-acai", quantity: 1, notes: "sem granola" },
      ],
      deliveryFee: 0,
      discount: 0,
      payments: [],
      fiscalStatus: "pending",
      whatsappStatus: "not_sent",
    },
    {
      id: "ord-102",
      unitId: "unit-ponta-verde",
      code: "102",
      channel: "delivery",
      status: "new",
      openedAt: "2026-05-03T11:18:00-03:00",
      customerId: "cust-maria",
      items: [
        { id: "item-102-1", productId: "prd-risoto", quantity: 1 },
        { id: "item-102-2", productId: "prd-tapioca", quantity: 1 },
      ],
      deliveryFee: 8,
      discount: 5,
      payments: [],
      fiscalStatus: "disabled",
      whatsappStatus: "queued",
    },
    {
      id: "ord-100",
      unitId: "unit-ponta-verde",
      code: "100",
      channel: "counter",
      status: "paid",
      openedAt: "2026-05-03T10:42:00-03:00",
      items: [{ id: "item-100-1", productId: "prd-acai", quantity: 2 }],
      deliveryFee: 0,
      discount: 0,
      payments: [
        {
          id: "pay-100",
          method: "pix",
          amount: 56,
          receivedAt: "2026-05-03T10:50:00-03:00",
        },
      ],
      fiscalStatus: "authorized",
      whatsappStatus: "not_sent",
    },
  ],
  cashSession: {
    id: "cash-0503",
    unitId: "unit-ponta-verde",
    openedBy: "usr-caixa",
    openedAt: now,
    openingAmount: 150,
    expectedAmount: 206,
    status: "open",
  },
  movements: [
    {
      id: "mov-1",
      unitId: "unit-ponta-verde",
      ingredientId: "ing-salmao",
      type: "receipt",
      quantity: 6.2,
      costImpact: 446.4,
      reason: "Recebimento Mar Azul",
      createdAt: "2026-05-01T09:12:00-03:00",
    },
    {
      id: "mov-2",
      unitId: "unit-ponta-verde",
      ingredientId: "ing-camarao",
      type: "waste",
      quantity: -0.4,
      costImpact: 23.2,
      reason: "Aparo acima do previsto",
      createdAt: "2026-05-03T08:50:00-03:00",
    },
  ],
  whatsappTemplates: [
    {
      id: "tpl-status",
      unitId: "unit-ponta-verde",
      name: "pedido_status_delivery",
      category: "utility",
      status: "approved",
    },
    {
      id: "tpl-promo",
      unitId: "unit-ponta-verde",
      name: "promocao_semana",
      category: "marketing",
      status: "draft",
      monthlyPrice: 30,
    },
  ],
};
