import type { SaboreData } from "./types";

const now = "2026-05-03T11:30:00-03:00";

export const demoData: SaboreData = {
  organization: {
    id: "org-sabore",
    name: "Sabore Pizza Demo",
    planPrice: 69.9,
  },
  unit: {
    id: "unit-ponta-verde",
    organizationId: "org-sabore",
    name: "Sabore Pizza Ponta Verde",
    city: "Maceio",
    neighborhood: "Ponta Verde",
    fiscalEnabled: true,
  },
  users: [
    {
      id: "usr-bruno",
      unitId: "unit-ponta-verde",
      name: "Bruno",
      role: "owner",
    },
    {
      id: "usr-caixa",
      unitId: "unit-ponta-verde",
      name: "Ana Caixa",
      role: "cashier",
    },
    {
      id: "usr-cozinha",
      unitId: "unit-ponta-verde",
      name: "Rafa Cozinha",
      role: "kitchen",
    },
  ],
  tables: [
    { id: "table-1", unitId: "unit-ponta-verde", label: "Mesa 1", seats: 2, status: "free" },
    { id: "table-2", unitId: "unit-ponta-verde", label: "Mesa 2", seats: 4, status: "free" },
    { id: "table-3", unitId: "unit-ponta-verde", label: "Mesa 3", seats: 6, status: "free" },
    { id: "table-4", unitId: "unit-ponta-verde", label: "Mesa 4", seats: 4, status: "free" },
  ],
  customers: [
    {
      id: "cust-maria",
      unitId: "unit-ponta-verde",
      name: "Maria Eduarda",
      phone: "+5582999991111",
      neighborhood: "Jatiuca",
    },
    {
      id: "cust-victor",
      unitId: "unit-ponta-verde",
      name: "Victor Lima",
      phone: "+5582999992222",
      neighborhood: "Ponta Verde",
    },
  ],
  ingredients: [
    {
      id: "ing-farinha",
      unitId: "unit-ponta-verde",
      name: "Farinha italiana 00",
      measure: "kg",
      averageCost: 5,
      minimumStock: 25,
    },
    {
      id: "ing-molho",
      unitId: "unit-ponta-verde",
      name: "Molho de tomate da casa",
      measure: "kg",
      averageCost: 10,
      minimumStock: 10,
    },
    {
      id: "ing-mussarela",
      unitId: "unit-ponta-verde",
      name: "Mussarela fatiada",
      measure: "kg",
      averageCost: 34,
      minimumStock: 12,
    },
    {
      id: "ing-calabresa",
      unitId: "unit-ponta-verde",
      name: "Calabresa artesanal",
      measure: "kg",
      averageCost: 28,
      minimumStock: 6,
    },
    {
      id: "ing-frango",
      unitId: "unit-ponta-verde",
      name: "Frango desfiado",
      measure: "kg",
      averageCost: 22,
      minimumStock: 6,
    },
    {
      id: "ing-catupiry",
      unitId: "unit-ponta-verde",
      name: "Catupiry bisnaga",
      measure: "kg",
      averageCost: 42,
      minimumStock: 4,
    },
    {
      id: "ing-pepperoni",
      unitId: "unit-ponta-verde",
      name: "Pepperoni",
      measure: "kg",
      averageCost: 48,
      minimumStock: 4,
    },
  ],
  lots: [
    {
      id: "lot-farinha-1",
      ingredientId: "ing-farinha",
      supplier: "Atacadao AL",
      batchCode: "FAR-0426",
      quantity: 50,
      expiresAt: "2026-08-20",
      receivedAt: "2026-04-25",
    },
    {
      id: "lot-molho-1",
      ingredientId: "ing-molho",
      supplier: "Ceasa",
      batchCode: "MOL-0501",
      quantity: 13.5,
      expiresAt: "2026-05-09",
      receivedAt: "2026-05-01",
    },
    {
      id: "lot-mussarela-1",
      ingredientId: "ing-mussarela",
      supplier: "Laticinio Sertao",
      batchCode: "MUS-0501",
      quantity: 8,
      expiresAt: "2026-05-06",
      receivedAt: "2026-05-01",
    },
    {
      id: "lot-calabresa-1",
      ingredientId: "ing-calabresa",
      supplier: "Casa das Carnes",
      batchCode: "CAL-0429",
      quantity: 7.2,
      expiresAt: "2026-05-08",
      receivedAt: "2026-04-29",
    },
    {
      id: "lot-frango-1",
      ingredientId: "ing-frango",
      supplier: "Avicola Ponta Verde",
      batchCode: "FRG-0502",
      quantity: 6.4,
      expiresAt: "2026-05-07",
      receivedAt: "2026-05-02",
    },
    {
      id: "lot-catupiry-1",
      ingredientId: "ing-catupiry",
      supplier: "Distribuidora Sul",
      batchCode: "CAT-0428",
      quantity: 4.8,
      expiresAt: "2026-05-12",
      receivedAt: "2026-04-28",
    },
    {
      id: "lot-pepperoni-1",
      ingredientId: "ing-pepperoni",
      supplier: "Casa das Carnes",
      batchCode: "PEP-0501",
      quantity: 3,
      expiresAt: "2026-05-07",
      receivedAt: "2026-05-01",
    },
  ],
  products: [
    {
      id: "prd-pizza-media",
      unitId: "unit-ponta-verde",
      name: "Pizza media - monte sua (30cm)",
      category: "Pizzas",
      price: 48,
      active: true,
      preparationArea: "kitchen",
    },
    {
      id: "prd-pizza-grande",
      unitId: "unit-ponta-verde",
      name: "Pizza grande - monte sua (35cm)",
      category: "Pizzas",
      price: 62,
      active: true,
      preparationArea: "kitchen",
    },
    {
      id: "prd-pizza-familia",
      unitId: "unit-ponta-verde",
      name: "Pizza familia - monte sua (40cm)",
      category: "Pizzas",
      price: 76,
      active: true,
      preparationArea: "kitchen",
    },
    {
      id: "prd-coca-lata",
      unitId: "unit-ponta-verde",
      name: "Coca-Cola lata 350 ml",
      category: "Refrigerantes",
      price: 7,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-coca-600",
      unitId: "unit-ponta-verde",
      name: "Coca-Cola 600 ml",
      category: "Refrigerantes",
      price: 9.5,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-coca-2l",
      unitId: "unit-ponta-verde",
      name: "Coca-Cola 2 litros",
      category: "Refrigerantes",
      price: 16.9,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-guarana-lata",
      unitId: "unit-ponta-verde",
      name: "Guarana Antarctica lata 350 ml",
      category: "Refrigerantes",
      price: 6.5,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-guarana-1l",
      unitId: "unit-ponta-verde",
      name: "Guarana Antarctica 1 litro",
      category: "Refrigerantes",
      price: 11,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-guarana-2l",
      unitId: "unit-ponta-verde",
      name: "Guarana Antarctica 2 litros",
      category: "Refrigerantes",
      price: 15.9,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-suco-laranja",
      unitId: "unit-ponta-verde",
      name: "Suco natural de laranja 500 ml",
      category: "Sucos",
      price: 10,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-suco-uva",
      unitId: "unit-ponta-verde",
      name: "Suco integral de uva 1 litro",
      category: "Sucos",
      price: 15,
      active: true,
      preparationArea: "bar",
    },
    {
      id: "prd-agua",
      unitId: "unit-ponta-verde",
      name: "Agua mineral 500 ml",
      category: "Bebidas",
      price: 4,
      active: true,
      preparationArea: "bar",
    },
  ],
  recipe: [
    { id: "rec-pizza-media-farinha", productId: "prd-pizza-media", ingredientId: "ing-farinha", quantity: 0.36 },
    { id: "rec-pizza-media-molho", productId: "prd-pizza-media", ingredientId: "ing-molho", quantity: 0.14 },
    { id: "rec-pizza-media-mussarela", productId: "prd-pizza-media", ingredientId: "ing-mussarela", quantity: 0.32 },
    { id: "rec-pizza-grande-farinha", productId: "prd-pizza-grande", ingredientId: "ing-farinha", quantity: 0.48 },
    { id: "rec-pizza-grande-molho", productId: "prd-pizza-grande", ingredientId: "ing-molho", quantity: 0.18 },
    { id: "rec-pizza-grande-mussarela", productId: "prd-pizza-grande", ingredientId: "ing-mussarela", quantity: 0.42 },
    { id: "rec-pizza-familia-farinha", productId: "prd-pizza-familia", ingredientId: "ing-farinha", quantity: 0.6 },
    { id: "rec-pizza-familia-molho", productId: "prd-pizza-familia", ingredientId: "ing-molho", quantity: 0.24 },
    { id: "rec-pizza-familia-mussarela", productId: "prd-pizza-familia", ingredientId: "ing-mussarela", quantity: 0.56 },
  ],
  orders: [
    {
      id: "ord-100",
      unitId: "unit-ponta-verde",
      code: "100",
      channel: "counter",
      status: "paid",
      openedAt: "2026-05-03T10:42:00-03:00",
      items: [
        {
          id: "item-100-1",
          productId: "prd-pizza-media",
          quantity: 1,
          name: "Media 30 cm Marguerita",
          unitPrice: 48,
          notes: "6 fatias. Sem adicionais.",
        },
        { id: "item-100-2", productId: "prd-guarana-lata", quantity: 1 },
      ],
      deliveryFee: 0,
      discount: 0,
      payments: [
        {
          id: "pay-100",
          method: "pix",
          amount: 54.5,
          receivedAt: "2026-05-03T10:50:00-03:00",
        },
      ],
      fiscalStatus: "authorized",
      whatsappStatus: "not_sent",
    },
  ],
  cashSession: {
    id: "cash-0503",
    unitId: "unit-ponta-verde",
    openedBy: "usr-caixa",
    openedAt: now,
    openingAmount: 150,
    expectedAmount: 204.5,
    status: "open",
  },
  movements: [
    {
      id: "mov-1",
      unitId: "unit-ponta-verde",
      ingredientId: "ing-mussarela",
      type: "receipt",
      quantity: 8,
      costImpact: 272,
      reason: "Recebimento Laticinio Sertao",
      createdAt: "2026-05-01T09:12:00-03:00",
    },
    {
      id: "mov-2",
      unitId: "unit-ponta-verde",
      ingredientId: "ing-molho",
      type: "waste",
      quantity: -0.6,
      costImpact: 6,
      reason: "Molho vencendo descartado na abertura",
      createdAt: "2026-05-03T08:50:00-03:00",
    },
  ],
  whatsappTemplates: [
    {
      id: "tpl-status",
      unitId: "unit-ponta-verde",
      name: "pedido_status_delivery",
      category: "utility",
      status: "approved",
    },
    {
      id: "tpl-promo",
      unitId: "unit-ponta-verde",
      name: "promocao_semana",
      category: "marketing",
      status: "draft",
      monthlyPrice: 30,
    },
  ],
};
